// Code generated by goctl. DO NOT EDIT.

export interface Res {
	code: number
	msg: string
	data: any
}

export interface Req {
}

export interface ReqParams {
	id: number
}

export interface GetWordRes {
	list: Array<Word>
}

export interface Word {
	word: string
	icon: string
	sound: string
}

export interface GetGameDdsRes {
	name: string
	totalTime: number
	standby: number
	hp: number
	probability: number
	guideline: string
}

export interface GetGameDyRes {
	name: string
	totalTime: number
	throwMaxLen: number
	gameLevel: number
	rotateMaxAngle: number
	randPaoMaxNum: number
	speed: number
	maxTime: number
	minTime: number
	probability: number
	guideline: string
	bgMusic: string
}

